### PR TITLE
Added Dockerfile for docker image build

### PR DESCRIPTION
**Pull request by pvr1**
Just a quick addition to enable containerization.

### CODE REVIEW

**Comment by MikeRalphson** [comment]
Thanks. See also #5, perhaps you and @ghostbody want to collaborate?

**Comment by pervrosen** [comment]
Did not see his addition. Pick the Dockerfile you prefer. I don’t think there is much to collaborate on left. 🙏🤗

**Comment by MikeRalphson** [comment]
Thanks.

**Comment by pervrosen** [comment]
Thank you for providing an excellent tool.

**Pull request closed without merging**
